DROP TABLE IF EXISTS entidad;

CREATE TABLE entidad (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
	tipo TEXT NOT NULL,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    nombre TEXT NOT NULL,
	nif TEXT NOT NULL,
	dir3 TEXT NOT NULL,
	direccion TEXT NOT NULL,
	cp TEXT NOT NULL,
	localidad TEXT NOT NULL,
	telefono TEXT NOT NULL
);

CREATE TABLE contacto (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    nombre TEXT NOT NULL,
	email TEXT NOT NULL,
	etiquetas TEXT NOT NULL,
	entidad_id INTEGER NOT NULL,
	FOREIGN KEY (entidad_id) REFERENCES entidad(id)
);

DROP TABLE IF EXISTS contacto;



